"""
Django settings for Tradexa project.

Generated by 'django-admin startproject' using Django 3.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-_rc(#%*fk74%b^4zk^4w73c=wdq-y_m#)ss#h1w++*ys*3pw#s'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

#ALLOWED_HOSTS = ["5.181.217.57","pankajtrsrewa.com","eshop.pankajtrsrewa.com","http://eshop.pankajtrsrewa.com/","www.eshop.pankajtrsrewa.com"]
ALLOWED_HOSTS = ["5.181.217.57","pankajtrsrewa.com","eshop.pankajtrsrewa.com","mysite.pankajtrsrewa.com"]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'store',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # 'store.auth.middleware.auth_middleware',

]

ROOT_URLCONF = 'Tradexa.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'Tradexa.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

from config import DATABASE_CONFIG
DATABASES = {
            'default': {
                        'ENGINE': 'django.db.backends.postgresql_psycopg2',
						'NAME': DATABASE_CONFIG['NAME'],
			            'USER': DATABASE_CONFIG['USER'],
			            'PASSWORD': DATABASE_CONFIG['PASSWORD'],
			            'HOST': DATABASE_CONFIG['HOST'],
			            'PORT': DATABASE_CONFIG['PORT'],

                   #     'NAME': 'eshop',
                   #     'USER': 'postgres',
                   #     'PASSWORD': "Dev-DB",
                   #     'HOST': '127.0.0.1',
                   #     'PORT': '5432',
                        'OPTIONS': {
                                  'client_encoding' : 'UTF8',
                                  #'options': '-c search_path=public,erp,general'
                                  #'options': '-c search_path=general',
                                  #'timezone:' : 'Asia/Kolkata',
                        }
                    }
            }




# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

STATIC_URL = '/static/'
# Manually add
MEDIA_URL= '/image/download/'
MEDIA_ROOT=BASE_DIR
import os
STATIC_ROOT = os.path.join(BASE_DIR, "static/")
# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

TIME_ZONE = 'Asia/Kolkata'
